title: Philip Todd
description: Senior Software Engineer | Azure Cloud Architect | Technical Leader

# theme: jekyll-theme-primer
remote_theme: pages-themes/architect@v0.2.0

plugins:
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-remote-theme # add this line to the plugins list if you already have one

relative_links:
  enabled: true
  collections: true

markdown: kramdown

exclude:
  - README.md