title: Philip Todd
description: Technology Leader | Senior Developer | Software Engineering
url: https://philiptodd.github.io
author: Philip Todd

theme: jekyll-theme-cayman

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

github_username: philiptodd
linkedin_username: philiptodd
